### ISSUE TITLE
Providing a zip archive doesn't help Cocoapods support

### ISSUE THREAD

**Issue by Zedenem** [rais38/comScore-iOS-SDK#1]
Hi @rais38,

I might be missing something here but how providing a ZIP archive helps the integration of ComScore using Cocoapods?

Shouldn't you provide the unzipped framework + header files + add details to the podspec on what requirements ComScore holds (`SystemConfiguration.framework` and `Security.framework` for the current version).

Looking forward to your answer. I will then be able to provide a pull request if it can help.

@Zedenem

**Comment by rais38** [comment]
Hi @Zedenem,

I really want is to have it in an accessible place the framework to give support to Cocoapods because it doesn't give official support. I was going to upload it to somewhere like Dropbox or AmazonS3 but I preferred it here in Github. I followed the style like [AppsFlyer](https://github.com/CocoaPods/Specs/blob/master/Specs/AppsFlyer-SDK/2.5.3.8/AppsFlyer-SDK.podspec.json).

You can find all details in [podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/comScore-iOS-SDK/3.1502.26/comScore-iOS-SDK.podspec.json) like `frameworks`, `vendored_libaries`...

Thank you for your comment 👍
